FROM rcb-img:latest

RUN mkdir -p /srv/rcb
RUN touch /srv/rcb/.rctRssConfig
RUN touch /srv/rcb/.rctJiraConfig

WORKDIR /opt/server/src
RUN ghc -optl-pthread -static -threaded -o /root/rcb -main-is System.RCB.RCB System/RCB/RCB.hs
CMD /root/rcb
